### PR TITLE
Support for CPUs not allowing full-width writes

### PR DESCRIPTION
**Pull request by andreas-abel**

### CODE REVIEW

**Comment by andreas-abel** [comment]
Fixes #4

**Comment by obilaniu** [comment]
@andreas-abel Thanks for your effort to make my software better!

Since I'm not a Git master, do you know would I get your commit on my local machine on a separate branch, to let me review it and make a few edits, then merge it into `master` while crediting you?

Anyways, can you add this ASCII art to the MSR notes at the bottom of the file, sorted by MSR #? I'm trying to save all the MSRs I'm using in one convenient list.
```c
/** 345   IA32_PERF_CAPABILITIES     -  Performance Capabilities Enumeration
 * 
 *                     /63/60 /56     /48     /40     /32     /24     /16     /08     /00
 *                    {..................................................##############}
 *                                                                       |||  ||||    |
 *     Full-Width Write -------------------------------------------------^||  ||||    |
 *     SMM Freeze --------------------------------------------------------^|  ||||    |
 *     PEBS Record Format -------------------------------------------------^^^^|||    |
 *     PEBS Arch Regs ---------------------------------------------------------^||    |
 *     PEBS Trap ---------------------------------------------------------------^|    |
 *     LBR Format ---------------------------------------------------------------^^^^^^
 */
```

**Comment by andreas-abel** [comment]
@obilaniu Thank you for making your software available to others! It would have cost me a lot of time to figure all of this out myself!

I'm no expert on Github either, but I think you could clone my fork of the project using 
`git clone https://github.com/andreas-abel/libpfc.git`,
checkout the branch of the pull request using
`git checkout full_width_writes`,
and then make your changes there and push them to this branch.

You can then merge it into the master branch as described here: https://help.github.com/articles/merging-a-pull-request/

**Comment by obilaniu** [comment]
@andreas-abel I've merged in your change, and added a check for CPUs that don't even have Performance Monitoring, and thus no MSR `IA32_PERF_CAPABILITIES`.

I've also added an `AUTHORS.md` file; You're more than welcome to append yourself to it, using whatever name you're comfortable with.

**Pull request merged**
